### PR TITLE
Sanitize date header

### LINKED ISSUE #32: Fatal Error if current language file contains '(' or ')' characters in PO-Revision-Date header
If a site has an existing theme/plugin language file, and that language file contains a `PO-Revision-Date` header with a character `DateTime` cannot parse such as `(` or `)`, Traduttore Registry throws this error:

```
2020-02-27 13:28:20.640776 [NOTICE] … [STDERR] PHP Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (Tue Dec 22 2015 12:52:19 GMT+0100 (West-Europa ) at position 39 (-): Unexpected character in /home/user/domains/example.com/public_html/wp-content/themes/genesis/lib/vendor/traduttore.php:85
Stack trace:
#0 /home/user/domains/example.com/public_html/wp-content/themes/genesis/lib/vendor/traduttore.php(85): DateTime->__construct('Tue Dec 22 2015...')
#1 /home/user/domains/example.com/public_html/wp-includes/class-wp-hook.php(290): Required\Traduttore_Registry\{closure}(Object(stdClass))
#2 /home/user/domains/example.com/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(stdClass), Array)
#3 /home/user/domains/example.com/public_html/wp-includes/option.php(1800): apply_filters('site_transient_...', Object(stdClass), 'update_themes')
#4 /home/user/domains/example.com/public_html/wp-includes/update.php(665): get_site_transient('update_themes')
#5 /home/user/domains/example in /home/user/domains/example.com/public_html/wp-content/themes/genesis/lib/vendor/traduttore.php on line 85
```
## Example PO-Revision-Date headers that break Traduttore Registry
These were both reported in the wild from production sites (ends are clipped because the stack trace was generated at that point):

- `"PO-Revision-Date: Tue Dec 22 2015 12:52:19 GMT+0100 (West-Europa"`
- `"PO-Revision-Date: Tue Jan 12 2016 15:04:22 GMT+0100 (Romance "`

The issue is the opening `(` and closing `)` characters, which DateTime cannot parse: https://3v4l.org/GIE5E

## Suggested fix
One fix would be to fall back to the Unix epoch if `DateTime` cannot parse the revision date string.

This assumes it's safe to treat unparseable `PO-Revision-Date` headers as older than the version on the server, which is probably reasonable.

```diff
				if ( $translation['updated'] && isset( $installed_translations[ $slug ][ $translation['language'] ] ) ) {
-					$local  = new DateTime( $installed_translations[ $slug ][ $translation['language'] ]['PO-Revision-Date'] );
+					try {
+						$local = new DateTime( $installed_translations[ $slug ][ $translation['language'] ]['PO-Revision-Date'] );
+					} catch (Exception $e) {
+						$local = new DateTime('1970-01-01');
+					}
+
					$remote = new DateTime( $translation['updated'] );

					if ( $local >= $remote ) {
						continue;
					}
				}
					
```

### PR DESCRIPTION
**Pull request by nickcernis**
Fixes #32 by ensuring that characters sometimes found in `PO-Revision-Date` headers such as '(' and ')' do not cause a fatal error.

The strategy as discussed in #32 is to:

- Use the date string up to the first '(' character.
- Fall back to the Unix epoch if the date still can not be parsed.

Catching `DateTime` construction with a fallback is not common (it's more common to just throw an exception if a provided date is bad). In this case it feels safer, though, because broken strings in translation files will otherwise cause WP sites to throw a fatal error during the translation update process.

An alternative would be to:

- Keep the logic around parsing the date before the first '('.
- Remove the try-catch block and only fix other DateTime parsing issues as we encounter them.

### CODE REVIEW

File: tests/phpunit/tests/SanitizeDate.php [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+		$dates_with_timezones = [
+			[
+				'input'    => 'Tue Jan 12 2016 15:04:22 GMT+0100 (Romance Standard Time)',
+				'expected' => 'Tue Jan 12 2016 15:04:22 GMT+0100'
+			],
+			[
+				'input'    => 'Tue Dec 22 2015 12:52:19 GMT+0100 (West-Europa)',
+				'expected' => 'Tue Dec 22 2015 12:52:19 GMT+0100',
+			],
+		];
```
Comment (ocean90) [inline tests/phpunit/tests/SanitizeDate.php]: We can simplify the test by using a [data provider](https://phpunit.readthedocs.io/en/9.0/writing-tests-for-phpunit.html#writing-tests-for-phpunit-data-providers) for both cases. There should also be a third case for an invalid date to check the return value in case of an exception.

Comment (nickcernis) [reply tests/phpunit/tests/SanitizeDate.php]: Thanks, @ocean90. I switched to a data provider and added a test for the return value for unparseable date strings.

**Comment by nickcernis** [comment]
@ocean90 Didn't mean to dismiss your review with my commit above. I'm done tweaking if you want to look again.
